name: Build and Test Pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Code
        uses: actions/checkout@v7

      - name: Run the Build Script
        run: ./scripts/build.sh
